name: Spring Boot CI/CD

# 언제 실행할지
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# 무엇을 할지
jobs:
  build-and-docker:
    # 어떤 환경에서
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Grant execute permission
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean build

      # 빌드된 파일이 있는지 확인 (디버깅용)
      - name: Check build artifact
        run: ls -l build/libs/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t spring-docker-cd .